apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  labels:
    app: test-pod
spec:
  containers:
    - name: test-pod
      image: original-image
      command: ["tail"]
      args: ["-f", "/dev/null"]
